Fix compiler panic on configurable initialization (#7068)
## Description

This PR fixes the compiler panic in the case of a configurable
initializer that couldn't be const evaluated, like e.g:
```sway
fn non_const_evaluable() -> u64 {
    asm() { fp: u64 }
}

configurable {
    CONFIG: u64 = non_const_evaluable(),
}
```

Instead of a panic:
```
thread 'main' panicked at sway-core/src/ir_generation/compile.rs:320:14:
called `Result::unwrap()` on an `Err` value: NonConstantDeclValue { span: Span { src (ptr): 0x564e0b311600, source_id: Some(SourceId(6291595)), start: 1009, end: 1019, as_str(): "CONFIG" } }
```
the compiler now emits an error:
```
CONFIG: u64 = non_const_evaluable(),
^^^^^^ Could not evaluate initializer to a const declaration.
```

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand
areas.
- [ ] I have updated the documentation where relevant (API docs, the
reference, and the Sway book).
- [ ] If my change requires substantial documentation changes, I have
[requested support from the DevRel
team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my
feature works.
- [ ] I have added (or requested a maintainer to add) the necessary
`Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs
Code Review
Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.