Install serde_with
The latest toml is failing because the Salt parsing is expecting &str
and the toml is returning String[1], erroing with this error

```
---- op::deploy::test::test_parse_and_validate_salts_pass stdout ----
thread 'op::deploy::test::test_parse_and_validate_salts_pass' panicked at 'called `Result::unwrap()` on an `Err` value: failed to parse manifest: TOML parse error at line 12, column 65
   |
12 | standalone_contract = { path = "../standalone_contract", salt = "0x0000000000000000000000000000000000000000000000000000000000000001" }
   |                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
invalid type: string "0x0000000000000000000000000000000000000000000000000000000000000001", expected a borrowed string
.', forc-plugins/forc-client/src/op/deploy.rs:360:89
```

The solution was install serde_with and use DisplayFromStr to by pass
the types serde and invoke FromStr direclty[1]. The ideal solution I
guess would be to patch the type[1]

[1] https://github.com/FuelLabs/fuel-vm/blob/master/fuel-types/src/array_types.rs#L323-L338