feat: return failed to fetch message for invalid registry lookups (#7205)
## Description

closes #7186.


Before this PR trying to get a non-existing package would result with:

```sh
error: Unable to deserialize a github registry lookup response. Body was: "404: Not Found"
```

Now we output:

```sh
Failed to fetch {pkg_name}
```

Which is a little bit cleaner in my opinion.