feat: improve error message in case of insufficient funds (#4762)
## Description
closes #4043.

Improves error message by stating the failure reason clearly if the
reason is insufficient funds. If the transaction is failing due to
insufficient funds we are outputing:

```console
Contract id: 0xa8f18533afc18453323bdf17c83750c556916ab183daacf46d7a8d3c633a40ee

Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
Do you accept to sign this transaction with fuel1egx2nvm4395gukm8uyh4zzxdlx3hht9ulu6n67nhwq57zs74camskx7klp [y/N]:y
Error: Deployment failed due to insufficient funds. Please be sure to have enough coins to pay for deployment transaction.
```

We will have a balance checking mechanism before signing the transaction
for test-net which would make this error only visible to manual signers
and people that are working against a local node.