better error and dca for configurables (#6121)
## Description

This PR closes https://github.com/FuelLabs/sway/issues/6118.

If for some reason an older `core` ends up being used, we now warn with
a more user-friendly error.

```
error: Configurables need a function named "abi_decode_in_place" to be in scope.
  --> /home/xunilrj/github/sway/test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw:42:5
   |
...
42 |     ARRAY_BOOL: [bool; 3] = [true, false, true],
   |     ^^^^^^^^^^
   |
   = help: Certify you are accessing a compatible version of the "core" library.
____
```

We also use a better span when warning about unused configurables.

```
warning
  --> /home/xunilrj/github/sway/test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw:47:5
   |
45 | 
46 | 
47 |     NOT_USED: u8 = 1,
   |     -------- This declaration is never used.
48 |     #[allow(dead_code)]
49 |     NOT_USED_BUT_ALLOWED: u8 = 2,
   |
____

  Compiled script "configurable_consts" with 1 warning.
```


## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand
areas.
- [ ] I have updated the documentation where relevant (API docs, the
reference, and the Sway book).
- [ ] If my change requires substantial documentation changes, I have
[requested support from the DevRel
team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my
feature works.
- [ ] I have added (or requested a maintainer to add) the necessary
`Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs
Code Review
Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

---------

Co-authored-by: Sophie Dankel <47993817+sdankel@users.noreply.github.com>
Co-authored-by: Igor Rončević <ironcev@hotmail.com>
Co-authored-by: Joshua Batty <joshpbatty@gmail.com>