Fix "Transaction collided" issue when running `run_on_node` tests (#7461)
## Description

This PR fixes non-deterministic "Transaction collided" error when
running `run_on_node` tests in parallel:

```console
{
    kind: Other,
    error: "Response errors;
            Transaction collided: Transaction with the same UTXO
            (id: 00000000000000000000000000000000000000000000000000000000000000010000)
            already exists and is more worth it"
}
```

The root-cause was using the same wallet to sign all transactions which
could sometimes end up in race conditions on the node. The PR now uses
five different wallets available on `fuel-core` local test instance and
executes tests in parallel over those five wallets, ensuring only
different wallets are used in parallel.

## Checklist

- [ ] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand
areas.
- [ ] I have updated the documentation where relevant (API docs, the
reference, and the Sway book).
- [ ] If my change requires substantial documentation changes, I have
[requested support from the DevRel
team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my
feature works.
- [ ] I have added (or requested a maintainer to add) the necessary
`Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs
Code Review
Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.