Optimizing AST Traversal with Adaptive Iteration (#5754)
## Description
Implements a new `adaptive_iter` method for use when traversing the
ASTs. If the size of the collection is less than 8, then regular
sequential iteration is used, otherwise a rayon parallel iterator is
used. I tested all values between 0-30 and found that 8 to be the sweet
spot. Less than this we don't see any benefit as the overhead for
spawning rayon threads isn't worth it.

This also fixes a stackoverlow error I noticed below. With this change,
we aren't overloading the rayon thread stack size when the recursion
level is quite deep.

```
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
error: test failed, to rerun pass `--test lib`

Caused by:
  process didn't exit successfully: `/Users/josh/Documents/rust/fuel/sway/target/debug/deps/lib-6ef1da655cf2d895 pedro --nocapture` (signal: 6, SIGABRT: process abort signal)
```