Implements where clauses for Structs and Enums. (#4557)
This commit enables where clauses for Structs and Enums and also adds
two kinds of error handling.

One for when a type does not implement a trait and is used in a data
structures that requires that trait.

And another for when a generic type parameter should have the trait
constraint.

Lets use the example below for demonstrating the two kinds of error
handling.
```rust
enum MyEnum<T> where T: MyAdd {
  X: T,
}
```
The enum above has a constraint where `T` should implement the trait
`MyAdd`.

When the type `MyEnum<u64>` is used and if `u64` does not implement the
trait `MyAdd` then the error `CompileError::TraitConstraintNotSatisfied`
is thrown.

The second type of error handling performed results in an error for the
example below.
```rust
fn add2<G>(e: MyEnum<G>) -> G {
}
```
When `MyEnum<G>` is used and the type parameter `G` does not have the
trait constraint `where G: MyAdd` then the error
`CompileError::TraitConstraintMissing` is thrown.

Fixes #1159

## Description


## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand
areas.
- [ ] I have updated the documentation where relevant (API docs, the
reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my
feature works.
- [x] I have added (or requested a maintainer to add) the necessary
`Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs
Code Review
Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.